<?php

namespace flowcode\wing\utils;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-07-11 at 01:09:15.
 */
class DateTimeTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var DateTime
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new DateTime;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers flowcode\wing\utils\DateTime::numberToName
     * @todo   Implement testNumberToName().
     */
    public function testNumberToName() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
