<?php

namespace flowcode\wing\utils\type;

class TestEntity {

    private $name;

    function __construct($name) {
        $this->name = $name;
    }

    public function getName() {
        return $this->name;
    }

}

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-08-24 at 11:24:39.
 */
class TypeJsonTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var TypeJson
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new TypeJson;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers flowcode\wing\utils\type\TypeJson::toJson
     * @todo   Implement testToJson().
     */
    public function testToJson() {
        $input = new TestEntity("test");
        $output = TypeJson::toJson($input);

        $this->assertEquals('{"name":"test"}', $output);
    }

}
